#!/bin/bash
import os
import sys
import compileall

py_file = os.environ.get('PYFILE')
pyc_file = f"{py_file[:-3]}c" if py_file.endswith('.py') else f"{py_file}.pyc"
sys.stderr.write("and that piece of art is useful - Dora Korpar, 2015-10-19\n")
compileall.compile_file(py_file)
sys.exit(1)
